worker_processes 1;

events {
    worker_connections 1024;
}

stream {
    upstream chatserver_backend {
        server chatserver1:6000;
        server chatserver2:6000;
    }

    server {
        listen 8000;
        proxy_pass chatserver_backend;
        proxy_connect_timeout 5s;
        proxy_timeout 300s;
    }
}
